aws-controllers-k8s/iam-controller

.gitignore, ATTRIBUTION.md, CONTRIBUTING.md, GOVERNANCE.md, Makefile, OWNERS, OWNERS_ALIASES, README.md, SECURITY.md, generator.yaml, go.mod, metadata.yaml
Aligns to the readme/docs used from other ACK service controller
repositories and a generator.yaml that ignores all resources in IAM.
=> Bring in ACK common controller files

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, config/iam/recommended-inline-policy, generator.yaml, helm/templates/deployment.yaml, helm/values.yaml, pkg/resource/role/sdk.go, templates/hooks/role/sdk_create_post_set_output.go.tpl, templates/hooks/role/sdk_update_post_set_output.go.tpl, test/e2e/requirements.txt, test/e2e/tests/test_role.py
There really isn't an "active" or "available" status for Role resources
in IAM. Basically, when the role is successfully created or updated,
it's in sync with whatever the desired state of the role was. So, this
patch adds simple setters after successful create and update code paths
that ensures ResourceSynced condition of True is set on the Role CRs.
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> Ensure ResourceSynced condition set

helm/Chart.yaml, helm/crds/iam.services.k8s.aws_roles.yaml, helm/values.yaml
Please note the change to the Role CRD is correct. When regenerating
the IAM controller previously, I had to manually update the CRD
definition in `config/crd/bases` but forgot to update the associated
CRD definition in `helm/crds`, which this commit caught.
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> release artifacts for v0.0.2

config/iam/recommended-inline-policy, pkg/resource/role/hooks.go, pkg/resource/role/sdk.go, templates/hooks/role/sdk_read_one_post_set_output.go.tpl, templates/hooks/role/sdk_update_post_set_output.go.tpl, test/e2e/resources/role_simple.yaml, test/e2e/role.py, test/e2e/tests/test_role.py
Adds support for updating (adding/removing) Tags from a Role resource in
the IAM controller.
Unfortunately, the "standard" Tagris
ListTagsForResource/TagResource/UntagResource AWS Resource Group Tagging
API calls aren't supported for IAM. You need to use the IAM-specific
TagRole/UntagRole/ListRoleTags IAM API calls to work with tags on Role
resources.
Following patches will add support for the same tags on Policy
resources.
Issue: aws-controllers-k8s/community#1119
=> support updating Tags on Role resources

test/e2e/tests/test_policy.py, test/e2e/tests/test_role.py
* Add random suffix to test resource names
* If a test fails and resource does not get cleaned up, this helps prevent `ConflictException` during next test run
* Ideally tests should/will cleanup all the resources, but in the worst case, one resource leak should not block PRs
=> add random suffix to test resource names

apis/v1alpha1/ack-generate-metadata.yaml, go.mod, go.sum, helm/Chart.yaml, helm/templates/NOTES.txt, helm/values.yaml
* Update ACK runtime to v0.16.3
* Create release artifacts for v0.0.3 release
=> ACK Runtime Upgrade to v0.16.3

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, pkg/resource/policy/hooks.go, pkg/resource/policy/sdk.go, pkg/resource/role/hooks.go, templates/hooks/policy/sdk_read_one_post_set_output.go.tpl, templates/hooks/policy/sdk_update_post_set_output.go.tpl, test/e2e/policy.py, test/e2e/resources/policy_simple.yaml, test/e2e/tests/test_policy.py
Fixes https://github.com/aws-controllers-k8s/community/issues/1124
Adds custom hook code to support the `TagPolicy` and `UntagPolicy` SDK methods for adding, updating and deleting tags on the `Policy` custom resource.
=> Add support for Policy Tag updates

pkg/resource/role/hooks.go
The IAM API will throw an `InvalidInput` exception when attempting to add or delete an empty list of tags. This pull request adds a condition to guard against this.
=> Fix invalid input exception when updating tags

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, helm/templates/cluster-role-controller.yaml, helm/values.schema.json, helm/values.yaml, pkg/resource/policy/delta.go, pkg/resource/policy/hooks.go, pkg/resource/role/delta.go, pkg/resource/role/hooks.go, pkg/util/tags.go
Lists of Tag structs for both the Role and Policy resources were causing
incorrect Delta differences to be detected when the order of the structs
was different. This brings in some code from the sfn-controller project
to properly ignore differences in only ordering for tags.
Issue aws-controllers-k8s/community#1503
=> correct tag comparisons for Role and Policy

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, pkg/resource/group/sdk.go, pkg/resource/user/sdk.go, templates/hooks/group/sdk_update_post_build_request.go.tpl, templates/hooks/user/sdk_update_post_build_request.go.tpl, test/e2e/tests/test_group.py, test/e2e/tests/test_user.py
The code-generator isn't able to generate correct code for
`newUpdateRequestPayload`. More specifically it doesn't set the
`spec.path` to `input.NewPath`. The reason is that the code-generator
expects the SDK field and CR field names to be similar.
Currently we have a feature that allows the code-generator to set a
field from a different SDK field name. But not the other way around.
We can discuss the above in https://github.com/aws-controllers-k8s/community/issues/1532
=> Add hooks to set `User` and `Group` paths in their update requests

pkg/resource/role/hooks.go, pkg/resource/role/sdk.go, pkg/resource/user/hooks.go, pkg/resource/user/sdk.go, templates/hooks/role/sdk_update_post_set_output.go.tpl, templates/hooks/user/sdk_update_post_set_output.go.tpl, test/e2e/tests/test_role.py, test/e2e/tests/test_user.py
Currently the update code path for `Users` and `Role` doesn't support
updates for permissionBoundary field. This patch adds the necessary
hooks and helper functions to help with that.
=> Support `User` and `Role` permissions boundary updates

config/iam/recommended-inline-policy
This policy is needed to satisfy the current e2e test @ TestRole::test_crud
Following up on https://github.com/aws-controllers-k8s/iam-controller/pull/47/, we need to add `PutRolePermissionsBoundary` to the list of recommended policies that the controller should have.
Ran into this error when trying to run e2e tests; specifically, `TestRole::test_crud` was failing; examining the logs of the iam-controller pod being run revealed a 403 error complaining that the assumed role did not have the right to perform this action.
=> Add `iam:PutRolePermissionsBoundary` to `recommended-inline-policy`

config/iam/recommended-inline-policy
This policy is needed to satisfy the current e2e test @ `TestUser::test_crud`
Following up on https://github.com/aws-controllers-k8s/iam-controller/pull/47, we need to add PutUserPermissionsBoundary to the list of recommended policies that the controller should have.
Ran into this error when trying to run e2e tests; specifically, TestUser::test_crud was failing; examining the logs of the iam-controller pod being run revealed a 403 error complaining that the assumed role did not have the right to perform this action.
=> Add `iam:PutUserPermissionsBoundary` to `recommended-inline-policy`

test/e2e/tests/test_group.py, test/e2e/tests/test_policy.py, test/e2e/tests/test_role.py, test/e2e/tests/test_user.py
I'm going to be adding a number of e2e tests for verifying the resource reference functionality. Figured before I did that, would be good to migrate to pytest fixture-based e2e tests.
=> move to fixture-based e2e tests

test/e2e/resources/role_referring.yaml, test/e2e/tests/test_references.py
Adds an e2e test that verifies resource references (at least from Role -> Policy) are working as expected.
Issue aws-controllers-k8s/community#1610
=> add resource reference e2e test

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, apis/v1alpha1/role.go, apis/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/iam.services.k8s.aws_roles.yaml, generator.yaml, helm/crds/iam.services.k8s.aws_roles.yaml, pkg/resource/role/delta.go, pkg/resource/role/hooks.go, pkg/resource/role/manager.go, pkg/resource/role/sdk.go, templates/hooks/role/sdk_create_post_set_output.go.tpl, templates/hooks/role/sdk_delete_pre_build_request.go.tpl, templates/hooks/role/sdk_read_one_post_set_output.go.tpl, templates/hooks/role/sdk_update_pre_build_request.go.tpl, test/e2e/role.py, test/e2e/tests/test_role.py
Adds support for inline policies for Role resources.
The new `Role.Spec.inlinePolicies` field is a `map[string]*string`, keyed by the inline policy *name* and valued with the inline policy *document* (serialized JSON string).
Inline policies are actually added and removed from a Role using different IAM API calls than their *managed policy* counterparts. Whereas managed policies (contained in the `Role.Spec.Policies` field) are attached and detached from the Role using the `AttachPolicyRole` and `DetachRolePolicy` API calls, the inline policies are attached and detached from the Role using the `AddRolePolicy` and `DeleteRolePolicy` API calls. Yes, this is confusing and why I hadn't actually included inline policies from the very beginning (I did not realize these were separate things and …
=> support Role.inlinePolicies

pkg/resource/group/hooks.go, pkg/resource/role/hooks.go, pkg/resource/user/hooks.go, pkg/util/map.go
For the inline policies, I used `github.com/samber/lo.Difference` function to compare two sets of k/v pairs. Unfortunately, I forgot to dereference the `*string` values of the inline policy `map[string]*string` into a `map[string]string` before doing so, which meant that the `lo.Difference` function was comparing against pointer values.
Fixes issue aws-controllers-k8s/community#1735
=> ensure comparing maps of strings not pointers

apis/v1alpha1/ack-generate-metadata.yaml, pkg/resource/role/hooks.go, pkg/resource/role/sdk.go, templates/hooks/role/sdk_update_pre_build_request.go.tpl, test/e2e/role.py, test/e2e/tests/test_role.py
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1448, but this also includes `AssumeRolePolicyDocument` in general as these are not updated regardless of whether the document change is valid or not.
Adds a call to sync the `spec.assumeRolePolicyDocument` object, alongside the corresponding AWS API calls.
=> feat: sync assume role policy document

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, helm/crds/services.k8s.aws_adoptedresources.yaml, helm/templates/_helpers.tpl, helm/values.schema.json, helm/values.yaml, pkg/resource/role/manager.go, templates/hooks/role/sdk_create_post_set_output.go.tpl, test/e2e/tests/test_role.py
The IAM CreateRole API response always has a nil Description field, even if the CreateRole API request contains a non-nil Description field. This is totally broken behaviour that also exists for the CreatePolicy API but apparently won't be fixed by IAM. So, this commit papers over that flaw in the API by late-initializing Role.Description to the (correct) non-nil value from the DescribeRole API response.
Fixes Issue aws-controllers-k8s/community#1772
=> late initialize Role.Description

pkg/resource/role/hooks.go, test/e2e/tests/test_role.py
The bug occurs when updating an existing item in `spec.inlinePolicies`.
The code incorrectly includes both the old(to remove) and new(to
add)values when using `lo.Difference`. This causes the code to first
attempt to replace the xisting policies with a call to
`iam::PutRolePolicy` and then mistakenly "delete" them right after.
This patch fixes this bug by calling `lo.Find` to double check whether
we need to keep an inline policy (if it only needs to be updated)
=> Fix bug in updating `spec.inlinePolicies`

pkg/resource/group/hooks.go, test/e2e/requirements.txt, test/e2e/tests/test_group.py
The bug occurs when updating an existing item in `spec.inlinePolicies`.
The code incorrectly includes both the old(to remove) and new(to
add)values when using `lo.Difference`. This causes the code to first
attempt to replace the xisting policies with a call to
`iam::PutGroupPolicy` and then mistakenly "delete" them right after.
This patch fixes this bug by calling `lo.Find` to double check whether
we need to keep an inline policy (if it only needs to be updated)
=> Fix bug in updating `group.spec.inlinePolicies`

pkg/resource/user/hooks.go, test/e2e/requirements.txt, test/e2e/tests/test_user.py
Issue https://github.com/aws-controllers-k8s/community/issues/1906
The bug occurs when updating an existing item in `spec.inlinePolicies`.
The code incorrectly includes both the old(to remove) and new(to
add)values when using `lo.Difference`. This causes the code to first
attempt to replace the xisting policies with a call to
`iam::PutUserPolicy` and then mistakenly "delete" them right after.
This patch fixes this bug by calling `lo.Find` to double check whether
we need to keep an inline policy (if it only needs to be updated)
=> Fix bug in updating `user.spec.inlinePolicies`

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, go.mod, go.sum, pkg/resource/role/delta.go, pkg/resource/role/hooks.go, test/e2e/tests/test_role.py
Fixes https://github.com/aws-controllers-k8s/community/issues/1837 and https://github.com/aws-controllers-k8s/community/issues/1869
Addressed a bug in the Role reconciliation mechanism related to
the configuration of a multi-line `AssumeRolePolicyDocument` for
the `Role` resources. The problem was observed as an infinite loop
of requeues and update attempts by the controller. The root cause
was traced back to the behavior of the IAM api, which silently
removed spaces and newline character from the
`AssumeRolePolicyDocument`, leading to faulty comparisons during
the reconciliation process
This commit introduces a solution by using objects built by
unmarshalling the json bytes - and leveraging `reflect.DeepEqual` to
compare the desired and latest states. As a result, the reconciliation …
=> Fix Role reconciliation logic for `AssumeRolePolicyDocument`

apis/v1alpha1/ack-generate-metadata.yaml, config/crd/bases/iam.services.k8s.aws_groups.yaml, config/crd/bases/iam.services.k8s.aws_instanceprofiles.yaml, config/crd/bases/iam.services.k8s.aws_roles.yaml, config/crd/bases/iam.services.k8s.aws_users.yaml, go.mod, go.sum, helm/crds/iam.services.k8s.aws_groups.yaml, helm/crds/iam.services.k8s.aws_instanceprofiles.yaml, helm/crds/iam.services.k8s.aws_roles.yaml, helm/crds/iam.services.k8s.aws_users.yaml, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/values.schema.json, helm/values.yaml, pkg/resource/group/references.go, pkg/resource/instance_profile/references.go, pkg/resource/role/references.go, pkg/resource/user/references.go, test/e2e/conftest.py, test/e2e/resources/policy_simple_namespace.yaml, test/e2e/resources/role_referring_namespace.yaml, test/e2e/tests/test_references.py
Issue [#1777](https://github.com/aws-controllers-k8s/community/issues/1777)
* Adding new e2e test suites to validate our recently introduced feature ["cross namespace resource references"](https://github.com/aws-controllers-k8s/code-generator/pull/532). In order to test this feature, we added a new feature to allow new namespace creation, from which resources will be referenced (Policy in this case).
=> Add tests for cross namespace resource reference

test/e2e/tests/test_references.py
Making changes to [previous PR](https://github.com/aws-controllers-k8s/iam-controller/pull/112), to make sure namespaces are being tested
`@pytest.fixtures(scope="module")` don't pick up custom `@pytest.mark` so we changed the scope to `"function"`
=> fix(tests): pre-create the testing namespaces for cross-namespace resource references tests

pkg/resource/instance_profile/hooks.go, pkg/resource/open_id_connect_provider/hooks.go, test/e2e/tests/test_open_id_connect_provider.py
fix https://github.com/aws-controllers-k8s/code-generator/pull/565
Remove `getImmutableFieldChanges` from hooks to support cel immutability
=> remove getImmutableFieldChanges references from hooks

.gitignore, apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, config/crd/bases/iam.services.k8s.aws_groups.yaml, config/crd/bases/iam.services.k8s.aws_instanceprofiles.yaml, config/crd/bases/iam.services.k8s.aws_openidconnectproviders.yaml, config/crd/bases/iam.services.k8s.aws_policies.yaml, config/crd/bases/iam.services.k8s.aws_roles.yaml, config/crd/bases/iam.services.k8s.aws_servicelinkedroles.yaml, config/crd/bases/iam.services.k8s.aws_users.yaml, generator.yaml, helm/crds/iam.services.k8s.aws_groups.yaml, helm/crds/iam.services.k8s.aws_instanceprofiles.yaml, helm/crds/iam.services.k8s.aws_openidconnectproviders.yaml, helm/crds/iam.services.k8s.aws_policies.yaml, helm/crds/iam.services.k8s.aws_roles.yaml, helm/crds/iam.services.k8s.aws_servicelinkedroles.yaml, helm/crds/iam.services.k8s.aws_users.yaml, helm/crds/services.k8s.aws_adoptedresources.yaml, helm/crds/services.k8s.aws_fieldexports.yaml, pkg/resource/open_id_connect_provider/manager.go, test/e2e/bootstrap_resources.py, test/e2e/resources/open_id_connect_provider_no_thumbprint.yaml, test/e2e/service_bootstrap.py, test/e2e/tests/test_open_id_connect_provider.py
Issue #, if available: [2450](https://github.com/aws-controllers-k8s/community/issues/2450)
Update the OpenID Connect Provider resource to late initialize the Thumbprints field when not provided. This avoids invalid requests being made to `UpdateOpenIDConnectProviderThumbprint` due to the Thumbprints field being nil.
- Mark `OpenIDConnectProvider.Thumbprints` as a late_initialize field in generator.yaml
- Add e2e test to verify that the Thumbprints field is populated with the value in AWS following creation of the resource and that subsequent reconcile doesn't trigger an invalid `UpdateOpenIDConnectProviderThumbprint` request.
- Add `.vscode` to `.gitignore`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Late Initialize OpenID Connect Provider Thumbprints
