- helm/Chart.yaml
- helm/values.yaml
Includes support for Role resources only.
> release artifacts for v0.0.1

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Includes update code path for Policy resources (#21)
> release artifacts for release v0.0.9

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Update release artifacts to version `v0.0.14`
> Release artifacts for release `v0.0.14`

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Update release version to `v0.0.15`
> Release artifacts for release `v0.0.15`

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
- release artifacts for release v0.0.22
> release artifacts for release `v0.0.22`

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/group.go
- apis/v1alpha1/open_id_connect_provider.go
- apis/v1alpha1/policy.go
- apis/v1alpha1/role.go
- apis/v1alpha1/types.go
- apis/v1alpha1/user.go
- go.mod
- go.sum
- helm/crds/iam.services.k8s.aws_groups.yaml
- helm/crds/iam.services.k8s.aws_policies.yaml
- helm/crds/iam.services.k8s.aws_roles.yaml
- helm/crds/iam.services.k8s.aws_users.yaml
- helm/templates/deployment.yaml
- helm/values.schema.json
- helm/values.yaml
> Update to ACK runtime v0.22.1

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
This release includes support for inline policies on Role, User and Group resources.
Issue: aws-controllers-k8s/community#1644
> release artifacts for v1.1.0

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Release artifact for release v1.1.2
> Release artifact for release v1.1.2

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Release artifact for release `v1.2.0`
> Release artifact for release `v1.2.0`

- config/iam/recommended-inline-policy
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1765
Updates the recommended inline policy to include `iam:UpdateAssumeRolePolicy`.
This builds from my previous work that was merged in https://github.com/aws-controllers-k8s/iam-controller/pull/74, as I did not update the recommended IAM policy at the same time.
> fix: update recommended inline policy to include `iam:UpdateAssumeRolePolicy`

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Release artifact for release `v1.2.3`
> Release artifact for release `v1.2.3`

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Release artifact for release v1.2.6
> Release artifact for release v1.2.6

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/templates/deployment.yaml
- helm/values.yaml
Updates the release version of IAM controller to v1.3.0
> Release artifacts for release v1.3.0

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
release artifacts for release `v1.3.1`
> release artifacts for release `v1.3.1`

- go.mod
- go.sum
Mainly bringing the new bug fixes from runtime to the iam controller:
- https://github.com/aws-controllers-k8s/runtime/pull/154
- https://github.com/aws-controllers-k8s/runtime/pull/153
> Pin ACK runtime to @dda2022eddbee55ef9cb342938e6bc9c4fd5ba28

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifacts for release v1.3.10

- apis/v1alpha1/ack-generate-metadata.yaml
- go.mod
- go.sum
- helm/values.yaml
- pkg/resource/group/manager_factory.go
- pkg/resource/instance_profile/manager_factory.go
- pkg/resource/open_id_connect_provider/manager_factory.go
- pkg/resource/policy/manager_factory.go
- pkg/resource/role/manager_factory.go
- pkg/resource/user/manager_factory.go
> Regenerate controller w/ code-gen@l3385813 and pin runtime to a606fd18

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/deployment.yaml
- config/controller/kustomization.yaml
- go.mod
- go.sum
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/templates/caches-role-binding.yaml
- helm/values.yaml
- pkg/resource/group/descriptor.go
- pkg/resource/group/resource.go
- pkg/resource/instance_profile/descriptor.go
- pkg/resource/instance_profile/resource.go
- pkg/resource/open_id_connect_provider/descriptor.go
- pkg/resource/open_id_connect_provider/resource.go
- pkg/resource/policy/descriptor.go
- pkg/resource/policy/resource.go
- pkg/resource/role/descriptor.go
- pkg/resource/role/resource.go
- pkg/resource/user/descriptor.go
- pkg/resource/user/resource.go
- test/e2e/bootstrap_resources.py
- test/e2e/resources/policy_adoption.yaml
- test/e2e/resources/role_adoption.yaml
- test/e2e/service_bootstrap.py
- test/e2e/tests/test_policy.py
- test/e2e/tests/test_role.py
> Add Adoption by annotation logic and tests

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Issue #, if available:
New release to support IAM service linked role
> release artifacts for release v1.4.0

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Issue #, if available: Fixes [2450](https://github.com/aws-controllers-k8s/community/issues/2450)
> Release artifacts for release v1.5.2
